In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2, RFE
from sklearn .tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"Pima.csv")
df.head()

Unnamed: 0  preg  plas  pres  skin  test  mass   pedi  age  class
0           0     6   148    72    35     0  33.6  0.627   50      1
1           1     1    85    66    29     0  26.6  0.351   31      0
2           2     8   183    64     0     0  23.3  0.672   32      1
3           3     1    89    66    23    94  28.1  0.167   21      0
4           4     0   137    40    35   168  43.1  2.288   33      1

In [3]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [4]:
test = SelectKBest(score_func=chi2, k=5)
chi = test.fit(x,y)

In [5]:
chi.scores_

array([ 200.96150445,  111.51969064, 1411.88704064,   17.60537322,
         53.10803984, 2175.56527292,  127.66934333,    5.39268155,
        181.30368904])

In [6]:
x.columns

Index(['Unnamed: 0', 'preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi',
       'age'],
      dtype='object')

In [7]:
chidf = pd.DataFrame(chi.scores_).T
chidf.columns=x.columns

In [8]:
chidf 

Unnamed: 0        preg         plas       pres      skin         test  \
0  200.961504  111.519691  1411.887041  17.605373  53.10804  2175.565273   

         mass      pedi         age  
0  127.669343  5.392682  181.303689

# RFE

In [9]:
lg = LogisticRegression()

rfe = RFE(lg, n_features_to_select=5)

rfe.fit(x,y)

RFE(estimator=LogisticRegression(), n_features_to_select=5)

In [10]:
rfe.ranking_

array([5, 1, 1, 2, 3, 4, 1, 1, 1])

In [11]:
rfe.support_

array([False,  True,  True, False, False, False,  True,  True,  True])

In [12]:
rfe_df = pd.DataFrame(rfe.ranking_).T
rfe_df.columns =x.columns
rfe_df

Unnamed: 0  preg  plas  pres  skin  test  mass  pedi  age
0           5     1     1     2     3     4     1     1    1

# Tree Based approach

In [15]:
dt = DecisionTreeClassifier (criterion='entropy')

In [16]:
dt.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [20]:
dt_dt=pd.DataFrame(dt.feature_importances_).T
dt_dt.columns = x.columns
dt_dt

Unnamed: 0      preg      plas      pres      skin      test      mass  \
0    0.106486  0.055762  0.260782  0.073946  0.031982  0.027522  0.189699   

       pedi       age  
0  0.129037  0.124786

- univariate selection:
   
   -Test, plasma, Age,Mass
   
 - RFE
  
    -preg,plas,mass,pedi,age
    
  - Tree
     
    -plasma,Mass,pedi,age

# cross validation

In [21]:
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

In [24]:
kf =KFold (n_splits=10, random_state=1, shuffle=True)
score = cross_val_score(LogisticRegression(),x,y,cv=kf)

In [26]:
score.mean()

0.7474196855775802

In [27]:
#leave on out

In [28]:
df.shape

(768, 10)

In [30]:
le = LeaveOneOut()
le_score = cross_val_score(LogisticRegression(),x,y,cv= le)
le

LeaveOneOut()

In [31]:
le_score

array([1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 0., 1., 1.

In [32]:
le_score.mean()

0.7552083333333334